/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

////#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_behaviorsteps_t_hpp__
#define __exlcm_behaviorsteps_t_hpp__

#include "pathstep_t.hpp"

namespace exlcm
{

/// MAL 2017-04-26
class behaviorsteps_t
{
    public:
        int16_t    entity_type;

        int8_t     version_n;

        int8_t     valid_f;

        int64_t    ref_n;

        double     timestamp_sec;

        exlcm::pathstep_t behavior_steps[500];

        double     behavior_step_distance_along_route[500];

        int16_t    behavior_steps_count;

 };
}

#endif
