/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

////#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_behaviorstring_t_hpp__
#define __exlcm_behaviorstring_t_hpp__

#include <vector>
#include <string>

namespace exlcm
{

class behaviorstring_t
{
    public:
        int16_t    LineCnt;

        std::vector< std::string > Behavior;

 };
}

#endif
