/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_boundaryshapepoint_t_hpp__
#define __exlcm_boundaryshapepoint_t_hpp__


namespace exlcm
{

class boundaryshapepoint_t
{
    public:
        float      east_m;

        float      north_m;

        int64_t    lane_uid;

};
}

#endif
