/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_connection_intersection_t_hpp__
#define __exlcm_connection_intersection_t_hpp__


namespace exlcm
{

class connection_intersection_t
{
    public:
        int64_t    incoming_laneseg_uid;

        float      approach_heading_deg;

        int8_t     connection_index;

        int8_t     connection_priority;

};
}

#endif
