/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_connectiontrafficsign_t_hpp__
#define __exlcm_connectiontrafficsign_t_hpp__


namespace exlcm
{

class connectiontrafficsign_t
{
    public:
        int64_t    incoming_laneseg_uid;

        int16_t    connection_n;

        int8_t     sign_count;

        int8_t     sign[3];

        int8_t     sign_probability[3];

        float      station_m[3];

        float      offset_m[3];

};
}

#endif
