/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_crosslaneviewpoint_t_hpp__
#define __exlcm_crosslaneviewpoint_t_hpp__


namespace exlcm
{

class crosslaneviewpoint_t
{
    public:
        float      view_station_m;

        float      sensed_range;

        float      lane_dist;

};
}

#endif
