/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_intersection_t_hpp__
#define __exlcm_intersection_t_hpp__

#include <vector>
#include "boundaryshapepoint_t.hpp"
#include "connection_intersection_t.hpp"

namespace exlcm
{

class intersection_t
{
    public:
        int8_t     valid_f;

        int8_t     version_n;

        int16_t    rolling_count;

        double     timestamp_sec;

        int64_t    ref_n;

        int32_t    maplet_iteration_n;

        int64_t    uid;

        int8_t     description_sz[48];

        int16_t    Intersection_type;

        double     center_east_m;

        double     center_north_m;

        float      center_up_m;

        float      height_m;

        int16_t    boundary_shape_point_count;

        std::vector< exlcm::boundaryshapepoint_t > boundary_shape_point;

        int16_t    connection_count;

        std::vector< exlcm::connection_intersection_t > connection;

};

}

#endif
