/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_intersectioncrosslane_t_hpp__
#define __exlcm_intersectioncrosslane_t_hpp__

#include <vector>
#include "creepcrosslaneview_t.hpp"
#include "crosslaneviewpoint_t.hpp"

namespace exlcm
{

class intersectioncrosslane_t
{
    public:
        int64_t    intersection_uid;

        int64_t    incoming_lane_id;

        int16_t    known_traffic_signal_phase;

        int16_t    observed_traffic_signal_phase;

        int16_t    known_traffic_sign_state;

        int16_t    observed_traffic_sign_state;

        int8_t     intersecting_lane_count;

        std::vector< int64_t > intersecting_lane_ids;

        std::vector< int8_t > intersecting_lane_yield_state;

        std::vector< exlcm::creepcrosslaneview_t > intersecting_lane_crossview_creep_points;

        std::vector< exlcm::crosslaneviewpoint_t > current_intersecting_lane_view;

};
}

#endif
