/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_lanewidth_t_hpp__
#define __exlcm_lanewidth_t_hpp__


namespace exlcm
{

class lanewidth_t
{
    public:
        float      driving_width_m;

        float      distance_along_seg_m;

        float      dist_to_left_edge_m;

        float      dist_to_right_edge_m;

};
}

#endif
