/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_lanegappred_t_hpp__
#define __exlcm_lanegappred_t_hpp__


namespace exlcm
{

class lanegappred_t
{
    public:
        float      gap_time;

        float      gap_start_m;

        float      gap_end_m;

        float      gap_start_mps;

        float      gap_end_mps;

        float      gap_start_mpss;

        float      gap_end_mpss;

};
}

#endif
