/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_localization_t_hpp__
#define __exlcm_localization_t_hpp__


namespace exlcm
{

class localization_t
{
    public:
        int8_t     valid_f;

        int8_t     version_n;

        int16_t    rolling_count;

        double     timestamp_sec;

        int64_t    ref_n;

        int32_t    maplet_iteration_n;

        float      localization_confidence_fr;

        int16_t    localization_sources;

        int64_t    matched_laneseg_uid;

        float      matched_lane_station_m;

        float      matched_lane_lateral_offset_m;

        float      matched_lane_misalign_rad;

        float      matched_seg_fr;

        float      matched_point_fr;

        int64_t    matched_intersection_uid;

        float      dist_to_matched_intersection_m;

        int8_t     inside_intersection_f;

        int8_t     matched_conn_n;

};
}

#endif
