/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

////#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_locsegcoords_t_hpp__
#define __exlcm_locsegcoords_t_hpp__


namespace exlcm
{

/// Note: All sepecific parameters are now available in Localization_t!!!
class locsegcoords_t
{
    public:
        int8_t     valid_f;

        int8_t     version_n;

        int16_t    rolling_count;

        double     timestamp_sec;

        int64_t    ref_n;

        int64_t    laneseg_uid;

        double     along_m;

        double     offset_m;

        double     seg_fr;

        double     point_fr;

        int32_t    conn_n;

        int8_t     scratch_byte1;

        int8_t     scratch_byte2;

        int16_t    scratch_short;

        int32_t    scratch_int1;

        int32_t    scratch_int2;

        double     scratch_real1;

        double     scratch_real2;

};
}

#endif
