/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_mapletrequest_t_hpp__
#define __exlcm_mapletrequest_t_hpp__


namespace exlcm
{

class mapletrequest_t
{
    public:
        int8_t     valid_f;

        int8_t     version_n;

        int16_t    rolling_count;

        double     timestamp_sec;

        int64_t    ref_n;

        int16_t    request_type;

        double     request_param_1;

        double     request_param_2;

        double     request_param_3;

        double     request_param_4;

        int64_t    requested_item_uid;

};
}

#endif
