/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_pathstep_t_hpp__
#define __exlcm_pathstep_t_hpp__


namespace exlcm
{

class pathstep_t
{
    public:
        int32_t    step_index_n;

        int16_t    current_segment_group;

        int16_t    which_lane_n;

        int16_t    step_task;

        int16_t    step_rule;

        float      min_time_to_destination_s;

        float      posted_speed_lim_mps;

        float      average_driven_speed_mps;

        int16_t    target_segment_group;

        int16_t    target_lane_n;

        float      current_segment_station_m;

        float      target_segment_station_m;

        float      turn_angle_rad;

        int16_t    direction;

};
}

#endif
