/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_pathplan_t_hpp__
#define __exlcm_pathplan_t_hpp__

#include <vector>
#include "pathstep_t.hpp"

namespace exlcm
{

class pathplan_t
{
    public:
        int8_t     valid_f;

        int8_t     version_n;

        int16_t    rolling_count;

        double     timestamp_sec;

        int64_t    ref_n;

        int8_t     reroute_status;

        double     normalized_cost;

        double     gen_time_sec;

        double     start_latitude_deg;

        double     start_longitude_deg;

        double     start_odometer_m;

        double     end_latitude_deg;

        double     end_longitude_deg;

        double     end_odometer_estimate_m;

        int8_t     destination_included;

        int32_t    total_step_count;

        int32_t    starting_step_index_n;

        int32_t    included_step_count;

        std::vector< exlcm::pathstep_t > path_steps;

        int8_t     scratch_byte1;

        int8_t     scratch_byte2;

        int16_t    scratch_short;

        int32_t    scratch_int1;

        int32_t    scratch_int2;

        double     scratch_real1;

        double     scratch_real2;

 };

}

#endif
