/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_point_enu_t_hpp__
#define __exlcm_point_enu_t_hpp__


namespace exlcm
{

class point_enu_t
{
    public:
        float      east_m;

        float      north_m;

        float      up_m;

};
}

#endif
