/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_policycosts_t_hpp__
#define __exlcm_policycosts_t_hpp__

#include <string>
#include <vector>
#include "behaviorpolicycosts_t.hpp"

namespace exlcm
{

class policycosts_t
{
    public:
        double     TotalCost;

        exlcm::behaviorpolicycosts_t BehaviorPolicyCost;

        double     TrafficEfficiencyCost;

        double     PolicyTransitionCost;

        double     routeCost;

        double     routeTime;

        std::string alternaterouteNeeded;

        int8_t     segment_count;

        std::vector< int64_t > segment_uid;

        std::vector< int16_t > segment_group;

};
}

#endif
