/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_visualizerstates_t_hpp__
#define __exlcm_visualizerstates_t_hpp__


namespace exlcm
{

/**
 * MAL 2017-04-26
 * PP  2017-08-30 : added VERSION_N
 */
class visualizerstates_t
{
    public:
        int16_t    entity_type;

        int8_t     version_n;

        int8_t     valid_f;

        int64_t    ref_n;

        double     timestamp_sec;

        int8_t     ClosedLoopEnabled;

        int8_t     FreezeFrameOnLogPlayerPause;

};

}

#endif
