/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

//#include <lcm/lcm_coretypes.h>

#ifndef __exlcm_waypoint_t_hpp__
#define __exlcm_waypoint_t_hpp__


namespace exlcm
{

class waypoint_t
{
    public:
        float      station_m;

        float      east_m;

        float      north_m;

        float      up_m;

        float      heading_deg;

        float      v_mps;

        float      curve_im;

        float      grade_rad;

        float      bank_rad;

 };
}

#endif
